services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    environment:
      HOST: 0.0.0.0
      MYSQL_HOST: mysql-service
      MYSQL_DB_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      OPENSEARCH_NODE: http://opensearch-service:9200
      NODE_ENV: development
      PORT: 3000
      WATCHPACK_POLLING: 'true'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      mysql-service:
        condition: service_healthy
      opensearch-service:
        condition: service_started

  nginx-service:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  mysql-service:
    image: mysql:latest
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - '${MYSQL_DB_PORT}:3306'
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  # OpenSearch 서비스 설정
  # https://docs.opensearch.org/latest/install-and-configure/install-opensearch/docker/#sample-docker-compose-file-for-development
  opensearch-service:
    image: opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node
      DISABLE_INSTALL_DEMO_CONFIG: 'true'
      DISABLE_SECURITY_PLUGIN: 'true'
      OPENSEARCH_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - '9200:9200'
      - '9600:9600'
  opensearch-dashboards:
    build:
      context: .
      dockerfile: Dockerfile.opensearch-dashboards
    container_name: opensearch-dashboards
    depends_on:
      opensearch-service:
        condition: service_started
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - '5601' # Expose port 5601 for web access to OpenSearch Dashboards

volumes:
  mysql-data:
  opensearch-data:
